### ISSUE TITLE
Import issues with SDK

### ISSUE THREAD

**Issue by kanchan41** [pendo-io/pendo-mobile-sdk#247]
**Platform + Version**
Android
classpath 'com.android.tools.build:gradle:8.1.4'

**SDK Version**
       
 compileSdk 35 
    minSdk 21
        targetSdkVersion 34

**Java** 
  compileOptions {
        sourceCompatibility = 11
        targetCompatibility = 11
    }
**Framework**
Native

**Describe the bug**
Not able to import "import sdk.pendo.io.*;" in Application class

**To Reproduce**

**Expected behavior**

**Logs**
No logs, as we have import issues. 

**Sample Code**

1) Project Gradle 

<img width="945" alt="Image" src="https://github.com/user-attachments/assets/b2e29d61-6395-479d-bc1b-dae15192775e" />

2) App Gradle 

<img width="1505" alt="Image" src="https://github.com/user-attachments/assets/bf146045-6c84-4e47-a4e7-7343127ed983" />

    implementation (group:'sdk.pendo.io' , name:'pendoIO', version:'3.6.0.x', changing:true)
3) Application Class

<img width="439" alt="Image" src="https://github.com/user-attachments/assets/c6d1bb77-1bcb-409f-b498-9062826ecbd3" />

**Additional context**
Have tried many steps, added latest manual SDK , and through URL , but nothing seems to be working.

**Comment by randmaayan** [comment]
hey @kanchan41, we had an issue with the manual installation that is now fixed, so please try to download again (we have released 3.7)

also, after downloading, please open the zip, and refer the url to unzipped dir.
For example, I downloaded to my downloads, this is what my path looks like - 

`url = uri("../../../../Downloads")`

Hoping this helps & waiting for your answer!

**Comment by kanchan41** [comment]
If I'm adding `allprojects { repositories { maven { url = uri("https://software.mobile.pendo.io/artifactory/androidx-release") } mavenCentral() google() } }`
Complete Gradle is giving error. Project sync is not working at all.

**Comment by kanchan41** [comment]
I tried this url `    implementation (group:'sdk.pendo.io' , name:'pendoIO', version:'3.7+', changing:true)`

Still facing error , with manual install also.

**Comment by Musab-Disi** [comment]
@kanchan41 To better understand the issue and help you faster, could you please provide:

- Your full build.gradle (or build.gradle.kts) file (both module-level and project-level if possible).

- Any relevant settings from settings.gradle (e.g., if you are including builds or using dependency substitution).

- Exact error messages you're seeing (full stack trace, not just the top line).

- Kotlin version (if you're using Kotlin in your project).

- Are you using any custom Gradle configuration (e.g., buildSrc, version catalogs)?

- Is this your first time integrating our SDK?

       - If not, what was the last SDK version that worked for you?

With this information, we'll be able to troubleshoot much more effectively. Thanks a lot!

**Comment by kanchan41** [comment]
1) Your full build.gradle (or build.gradle.kts) file (both module-level and project-level if possible).

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    /* repositories {
         mavenCentral()
         maven {
 //            url 'https://maven.google.com/'
             //              url = uri("/path/to/local/file")
             //            url = uri("/Users/kanchan.vaishnav/StudioProjects/adaptiveworks/android/pendoIO-3.6.4.7459.aar")
             //            url 'https://pendo.jfrog.io/artifactory/android-sdk'
             url = uri("https://software.mobile.pendo.io/artifactory/androidx-release")
             //            url = uri("https://sdk.pendo.io/maven/")
             name 'Google'
         }
         google()
         mavenCentral()
     }*/


    /*  repositories {
          google()
          mavenCentral()
          maven {
              url "https://maven.google.com"
          }
          maven {
              url = uri("/Users/kanchan.vaishnav/Downloads/sdk")

              //  url = uri("https://software.mobile.pendo.io/artifactory/androidx-release")
          }
      }
  */

//    allprojects {
        repositories {
            maven {
                url = uri("https://software.mobile.pendo.io/artifactory/androidx-release")
            }
            mavenCentral()
            google()
        }
//    }

        dependencies {
            classpath 'com.android.tools.build:gradle:8.9.2'
            classpath 'com.google.gms:google-services:4.4.2'
            classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.3'
        }
    }
`

2) Any relevant settings from settings.gradle (e.g., if you are including builds or using dependency substitution).

`include ':app'

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://software.mobile.pendo.io/artifactory/androidx-release")
        }
    }
}
`

3) Exact error messages you're seeing (full stack trace, not just the top line).

Error only with import SDK, apart from this build is success. 

4) Kotlin version (if you're using Kotlin in your project).

No Kotlin in project 

5) Are you using any custom Gradle configuration (e.g., buildSrc, version catalogs)?
No Custom Gradle

6) Is this your first time integrating our SDK?
Yes

7) If not, what was the last SDK version that worked for you?

SDK Version

compileSdk 35
minSdk 21
targetSdkVersion 34

**Comment by Musab-Disi** [comment]
The issue has been resolved 
Integration issue
Closing this
