### ISSUE TITLE
Pendo.h File Not Found After Pod Install

### ISSUE THREAD

**Issue by srachana1010** [pendo-io/pendo-mobile-sdk#249]
**Platform + Version**
iOS 12 (Deployment Target)
iOS 18.2 (iOS Simulator SDK)
macOS [14.7]
Xcode [16.2]

**SDK Version**
Pendo iOS SDK via CocoaPods (pod 'Pendo')
Pendo 3.7 (from Podfile.lock)

**Framework**
Native Objective-C

**Describe the bug**
After integrating the Pendo SDK using CocoaPods, the build fails with the error:
'Pendo.h' file not found, despite successful pod installation and the presence of Pendo.xcframework.

**To Reproduce**
1. Add pod 'Pendo' to Podfile and run pod install
2. Open .xcworkspace in Xcode
3. Import #import "Pendo.h" in AppDelegate.m
4. Try to build the project
5. Build fails with Pendo.h file not found

**Expected behavior**
Build should succeed and Pendo SDK should be usable in the app.

**Logs**
N/A

**Sample Code**
AppDelegate.m
<img width="733" alt="Image" src="https://github.com/user-attachments/assets/66aeb62a-ea0c-43f7-ad91-6f2c3300dbf0" />

**Additional context**
Pendo.xcframework exists and contains the headers in appropriate architecture folders.

**Comment by MikePendo** [comment]
@srachana1010 
That should resolve the issue and we will update the doc to the correct import

**Comment by srachana1010** [comment]
I tried using `@import Pendo;` and `#import <Pendo/Pendo.h>`, but the app still doesn't recognize the Pendo module.

**Comment by MikePendo** [comment]
mmm that super strange, 
Do you see pendo package in your pods?
Can you share sample project with that error? (maybe its something in the project path)

**Comment by MikePendo** [comment]
mmm so the problem seems to related to specific project configs. 
Maybe you could send us a small copy without content or please  schedule  a call and we will try to see what's going on

**Comment by srachana1010** [comment]
Could you please help schedule a call so we can check it?

**Comment by majd-pendo** [comment]
@srachana1010 Hello, I'm from the Technical Support team here at Pendo.
Before scheduling a call, can you send us the structure of your project so we can attempt to reproduce the behavior? We would be happy to facilitate a call, but I would prefer to have all the info on hand so we can provide you with the best answers
