### ISSUE TITLE
SPM Package descriptor url resource does not found (404)

### ISSUE THREAD

**Issue by bitmansofthu** [pendo-io/pendo-mobile-sdk#85]
**Platform + Version**
iOS 17

**SDK Version**
3.0.0.7964

**Framework**
SwiftUI

**Describe the bug**
When fetching packages XCode reports the following error:
`failed downloading 'https://software.mobile.pendo.io/artifactory/ios-sdk-release/swiftui/3.0.0.7964/pendo-ios-sdk-xcframework.3.0.0.7964.zip' which is required by binary target 'Pendo': badResponseStatusCode(404)`

**To Reproduce**
Reset package caches

**Expected behavior**
The file should be available for download to resolve the package,

**Comment by MaximShnirman** [comment]
@bitmansofthu issue should be fixed now, you can try again, thanks.

**Comment by bitmansofthu** [comment]
Thanks for your quick help!

**Comment by bitmansofthu** [comment]
Sorry, it seems that the file is still not available.
`failed downloading 'https://software.mobile.pendo.io/artifactory/ios-sdk-release/swiftui/3.0.0.7964/pendo-ios-sdk-xcframework.3.0.0.7964.zip' which is required by binary target 'Pendo': badResponseStatusCode(404)`

**Comment by bratxdy** [comment]
+1 this is still an issue and blocking us from releasing since we are on the swiftui branch and can't control versions. Has the swiftui branch been merged into master yet?

**Comment by MikePendo** [comment]
The swiftui branch was merged to 3.0, please _reset packages caches_  if needed and try to fetch once again
<img width="1324" alt="Screenshot 2023-11-29 at 18 22 35" src="https://github.com/pendo-io/pendo-mobile-sdk/assets/56674958/03e8d397-9623-4db0-8a38-b6610d8431d7">

**Comment by MikePendo** [comment]
I am closing the issue feel free to reach us if u still have an issue

**Comment by MikePendo** [comment]
@bratxdy @bitmansofthu 
My appologizes it  seems that the swiftui-beta is pointing to the 3.0 BUT  the reference is wrong.
As we have merged the swiftui in to 3.0 I would recommend to fetch the 3.0. We will see how to restore the old link

**Comment by MikePendo** [comment]
@bratxdy @bitmansofthu 
We have reverted swiftui branch to the original one. So now you can fetch the beta and move to 3.0 when u r ready. (Recommended )

**Comment by noambartouv** [comment]
@bratxdy @bitmansofthu 
The full instructions to move to 3.0 can be found here: 
[https://github.com/pendo-io/pendo-mobile-sdk/blob/master/migration-docs/ios-2.x-to-3.x-migration.md](https://github.com/pendo-io/pendo-mobile-sdk/blob/master/migration-docs/ios-2.x-to-3.x-migration.md)

**Comment by bitmansofthu** [comment]
Thanks for your help!
